### ISSUE TITLE
Install Guide? 

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [moeinfatehi/Admin-Panel_Finder#1]
Hi,

Please forgive me for asking this. Is there an installation guide? I keep getting errors when I attempt to install this extension in burp.

**Comment by moeinfatehi** [comment]
Hi,
One of the easiest ways is to open it in an IDE like netbeans and build the
project.
You will find the jar file in a new directory named "dist"
Then add the jar file in burp extensions tab.

**Comment by andreystepanov** [comment]
If you are on Linux, then follow these simple steps:

1. Install [Ant](http://ant.apache.org/). `sudo pacman -S ant` for Arch users
2. Clone current repository
3. `cd` into directory and run `ant jar`
4. Add new Burp Extention using `./dist/adminPanelFinder.jar` file

**Comment by moeinfatehi** [comment]
I also added the executable jar.
