### ISSUE TITLE
 build a java file for burp with the eclipse

### ISSUE THREAD

**Issue by wikihow33** [moeinfatehi/Admin-Panel_Finder#2]
please help how to build a java file for burp
with the eclipse?
https://prnt.sc/tctl8a

**Comment by andreystepanov** [comment]
If you are on Linux, then follow these steps:

1. Install [Ant](http://ant.apache.org) - `sudo pacman -S ant` for Arch users

**Comment by andreystepanov** [comment]
If you are on Linux, then follow these simple steps:

1. Install [Ant](http://ant.apache.org/). `sudo pacman -S ant` for Arch users
2. Clone current repository
3. `cd` into directory and run `ant jar`
4. Add new Burp Extention using `./dist/adminPanelFinder.jar` file

**Comment by moeinfatehi** [comment]
The executable jar file was added.
